"""Stage 3: Interactive terminal checkpoint for human-in-the-loop review."""

import json
from pathlib import Path
from typing import Any, Optional, Set, Union

from src.models import ReviewOverride


def display_predictions(predictions: list[dict[str, Any]]) -> None:
    """Displays predicted category and priority for each ticket in a clean terminal table."""
    print("\n" + "=" * 65)
    print(f"{'TICKET ID':<12} | {'PREDICTED CATEGORY':<22} | {'PRIORITY':<10}")
    print("-" * 65)
    for pred in predictions:
        t_id = pred.get("ticket_id", "")
        cat = pred.get("category", "")
        prio = pred.get("priority", "")
        print(f"{t_id:<12} | {cat:<22} | {prio:<10}")
    print("=" * 65 + "\n")


def parse_and_validate_override(
    raw_input: str,
    predictions_by_id: dict[str, dict[str, Any]],
    allowed_categories: Set[str],
    allowed_priorities: Set[str],
) -> Optional[ReviewOverride]:
    """Validates the CSV override string against allowed config values and existing ticket IDs."""
    parts = [p.strip() for p in raw_input.split(",")]
    if len(parts) != 3:
        print(
            "  ❌ Format error: Expected 3 comma-separated values: ticket_id,category,priority"
        )
        return None

    ticket_id, new_category, new_priority = parts

    if ticket_id not in predictions_by_id:
        print(f"  ❌ Invalid ticket_id: '{ticket_id}' not found in current batch.")
        return None

    if new_category not in allowed_categories:
        print(
            f"  ❌ Invalid category '{new_category}'. Allowed: {sorted(list(allowed_categories))}"
        )
        return None

    if new_priority not in allowed_priorities:
        print(
            f"  ❌ Invalid priority '{new_priority}'. Allowed: {sorted(list(allowed_priorities))}"
        )
        return None

    original = predictions_by_id[ticket_id]
    return ReviewOverride(
        ticket_id=ticket_id,
        old_category=original["category"],
        new_category=new_category,
        old_priority=original["priority"],
        new_priority=new_priority,
    )


def run_review_checkpoint(
    predictions: list[dict[str, Any]],
    config: dict[str, Any],
    output_path: Union[str, Path] = "review_overrides.json",
) -> list[dict[str, Any]]:
    """Runs the terminal human review loop, captures overrides, and writes review_overrides.json.

    Args:
        predictions: list of prediction dictionaries generated by LLM triage.
        config: Loaded triage_config dictionary containing validation constraints.
        output_path: Destination path for review_overrides.json.

    Returns:
        list of serialized override dictionaries.
    """
    display_predictions(predictions)

    allowed_categories = set(config.get("allowed_categories", []))
    allowed_priorities = set(config.get("allowed_priorities", []))
    predictions_by_id = {p["ticket_id"]: p for p in predictions}

    # dict keyed by ticket_id so that subsequent overrides for the same ticket replace previous ones
    overrides_map: dict[str, ReviewOverride] = {}

    print("Enter any overrides as: ticket_id,category,priority")
    print("Press Enter on an empty line when done.")

    while True:
        try:
            line = input("> ").strip()
        except (EOFError, KeyboardInterrupt):
            # Allows automated test fixtures or non-interactive pipe inputs to complete cleanly
            break

        if not line:
            break

        override = parse_and_validate_override(
            raw_input=line,
            predictions_by_id=predictions_by_id,
            allowed_categories=allowed_categories,
            allowed_priorities=allowed_priorities,
        )

        if override:
            overrides_map[override.ticket_id] = override
            print(
                f"  ✓ Recorded override for {override.ticket_id}: "
                f"[{override.old_category} -> {override.new_category}, "
                f"{override.old_priority} -> {override.new_priority}]"
            )

    serialized_overrides = [ov.model_dump() for ov in overrides_map.values()]

    out_file = Path(output_path)
    out_file.parent.mkdir(parents=True, exist_ok=True)
    with open(out_file, "w", encoding="utf-8") as f:
        json.dump(serialized_overrides, f, indent=2, ensure_ascii=False)

    print(
        f"\nReview checkpoint finished. Saved {len(serialized_overrides)} override(s) to {output_path}.\n"
    )
    return serialized_overrides
